notification/urls.py
from django.urls import path
from .views import set_notification, get_notification, fetch_notification_datas

urlpatterns = [
    path('set-notification', set_notification, name='set-notification'),
    path('get-notification', get_notification, name='get-notification'),
    path('notification-datas', fetch_notification_datas, name='notification-datas'),
    # path('notif-data', notif_data, name='notif-data')
]

quiz/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',start_session,name='start_session')
]

skin101/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import notification.urls as notification
import userprofile.urls as userprofile
import autentikasi.urls as autentikasi
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('notification.urls')),
    path('profile/', include('userprofile.urls')),
    path('', include('autentikasi.urls')),
    path('reviews/', include('reviews.urls')),
    path('quiz/',include('quiz.urls')),
    path('display/', include(('productdisplay.urls', 'productdisplay'))),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/models.py
from django.db import models


# Create your models here.
class Notification(models.Model):
    title = models.CharField(max_length=100)
    messages = models.TextField()

    def json(self):
        return {
            'title': self.title,
            'messages': self.messages,
        }

notification/forms.py
from django import forms
from django.forms import ModelForm
from .models import Notification as NotificationModel


class NotificationForm(ModelForm):
    class Meta:
        model = NotificationModel
        fields = ['title', 'messages']

notification/views.py
from django.shortcuts import redirect, render
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from .models import Notification
from .forms import NotificationForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@user_passes_test(lambda u: u.is_superuser)
def get_notification(request):
    form = NotificationForm(request.POST)
    if (request.method == 'POST'):
        if (form.is_valid()):
            notif = Notification(title="title", messages="messages")
            notif.save()
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'{username} has been made a notification for user!')
            print('balalalalal')
            return redirect('/administrator/')
    response = {'form': form}
    return render(request, 'set_notification.html', response)

# pake ini
@user_passes_test(lambda u: u.is_superuser)
def set_notification(request):
    form = NotificationForm(request.POST)
    if (request.method == 'POST'):
        print(form['title'].value())
        print(form['messages'].value())
        if (form.is_valid()):
            notif = Notification(title="title", messages="messages")
            notif.save()
            form.save()
            notif_data = {}
            notif_data['title'] = request.POST.get('title')
            notif_data['messages'] = request.POST.get('messages')
            print("OKEEE")
            return JsonResponse(notif_data, safe=False)
        print('bener kok post')
        return redirect('../home')
    elif (request.method == 'GET'):
        print('ini get bukan post')
    else:
        print('failed to post data')

    context = {
        'form': form,
    }
    return render(request, 'set_notification.html', context)



# @user_passes_test(lambda u: u.is_superuser)
@login_required
def fetch_notification_datas(request):
    form = Notification.objects.all().values()
    datas = serializers.serialize('json', form)
    print("datas: " + datas)
    response = {'form': form}
    return render(request, 'navbar_user.html', response)
    # return HttpResponse(response, content_type='application/json')

def notif_data(request):
    form = Notification.objects.all()
    data = serializers.serialize('json', form)
    print(form)
    print(data)
    return HttpResponse(data, content_type="applications/json")

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

notification/templates/make_notifications.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Skin101 - Make Skincare Notification </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/notification_styles.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </head>
  <body id="notification">
    {% include 'navbar_roles.html' %}

    <!-- Make Announcement -->
    <section class="container-fluid">
      <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-3">
          <form action="" method="POST" id="announcement" class="form-container">
              {% csrf_token %}
              <h4 class="text-center font-weight-bold">Make Announcement</h4>
              <br>
              <div class="form-group">
                <input id="id_title" class="form-control" width="75%" type="text" name="title" required="true" placeholder="Title" />
              </div>
              <div class="form-group">
                <textarea id="id_message" class="form-control" form="announcement" rows="4" cols="100" name="message" required="true" placeholder="Message"></textarea>
              </div>
              <br>
              <input type="submit" class="btn btn-primary btn-block" id="announcementSubmit" value="Post">
          </form>
        </section>
      </section>
    </section>
    <!-- end section -->

    <script type="text/javascript">
      $(document).ready(function() {
        $("#announcementSubmit").click(function(e) {
          // serialize the data for sending the form data.
          var serializedData = $(this).serialize();
          // make POST ajax call
          $.ajax({
            url: "{% url 'make_announcement' %}",
            type: "POST",
            data: serializedData,
            success: function(response) {
              location.reload();
            },
            error: function (response) {
              console.error(response);
            }
          });
        });
      })
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>

notification/templates/modal_notification.html
<!-- Modal Popup Announcement -->
{% block content %}
<div class="modal fade" id="notificationModal" data-keyboard="false" data-backdrop="static" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Notification</h4>
        <button class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">}
        <h5 style="text-align: center;">{{title}}</h5>
        <p style="text-align: center;" id="notificationTitle"></p>
        <br>
        <h5 style="text-align: center;">{{messages}}</h5>
        <p style="text-align: center;" id="notificationtMessage"></p>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- end modal -->
{% endblock %}

notification/templates/navbar_admin.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'autentikasi/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
  {% load static %}
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #7A9EAF;" id="main-navbar">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/in-logo-1.svg' %}" alt="" ></a>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="/home" style="color: #D2C8C8;" id="a">Home</a>
{#              <a class="nav-link active" aria-current="page" href="../administrator/set-notification">Set Notification</a>#}
            </div>
            <form class="d-flex" id="authstyle">
              {% if user.is_authenticated %}
{#                <i data-toggle="modal" data-target="#notificationModal" style="color: white; background-color: #fd5e14;" id="header-links" class="fa fa-bell"></i>#}
{#                  <a href="../administrator/set-notification" class="btn" style="color: #D2C8C8; background-color: #404969;"type="submit" id="header-links"> Set Notification </a>#}
                  <a href="{% url 'logout' %}" class="btn" style="color: #D2C8C8; background-color: #404969;"type="submit" id="header-links"> Logout </a>
              {% else %}
                <a href="{% url 'login' %}" class="btn" style="color: #D2C8C8; background-color: #404969; margin-left: 10px; "type="submit" id="header-links">Log In</a>
              {% endif %}
              </form>
          </div>
        </div>
    </nav>
  </head>
</html>

notification/templates/navbar_guest.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'autentikasi/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">

  </head>
  {% load static %}
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #7A9EAF;" id="main-navbar">
        <div class="container">
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="/home" style="color: #D2C8C8;" id="a">Home</a>
            </div>
            <form class="d-flex" id="authstyle">
                <ul id="ul-guest">
                    <li><a href="{% url 'register' %}" class="btn" style="color: #D2C8C8; background-color: #404969;"type="submit" id="header-links"> Create Account </a></li>
                    <li><a href="{% url 'login' %}" class="btn" style="color: #D2C8C8; background-color: #404969; margin-left: 10px; "type="submit" id="header-links">Log In</a></li>
                </ul>
            </form>
          </div>
        </div>
    </nav>
</html>

notification/templates/navbar_roles.html
<!-- Choosing navbar based on roles (Guest, User, or Admin) -->
{% if user.is_authenticated %}

	<!-- Admin -->
  {% if user.is_superuser %}
    {% include 'navbar_admin.html' %}

  <!-- User -->
  {% else %}
    {% include 'navbar_user.html' %}
  {% endif %}

<!-- Guest -->
{% else %}
  {% include 'navbar_guest.html' %}

{% endif %}

notification/templates/navbar_user.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'autentikasi/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">

  </head>
  <body id="bg" style="background-image: url({% static 'autentikasi/images/bg.png' %});">
  {% load static %}
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #7A9EAF;" id="main-navbar">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/in-logo-1.svg' %}" alt="" ></a>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="/home" style="color: #D2C8C8;" id="a" >Home</a>
{#            </div>#}
{#            <div class="d-flex" id="authstyle">#}
              {% if user.is_authenticated %}
                  <ul>
                    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
                      <li><a href="{% url 'productdisplay:index' %}" class="btn" style="color: #D2C8C8; background-color: #404969;" type="submit" id="header-links"> Product Display </a></li>
                      <li><a href="{% url 'review' %}" class="btn" style="color: #D2C8C8; background-color: #404969; text-align: center" type="submit" id="header-links"> Review </a></li>
                      <li><i data-bs-toggle="modal" data-bs-target="#notificationModal" style="color: #D2C8C8; background-color: #404969; margin-top: 5px" id="header-links" class="fa fa-bell"></i></li>
                      <li><a href="{% url 'profile' %}" class="btn" style="color: #D2C8C8; background-color: #404969; "type="submit" id="header-links"> Profile </a></li>
                      <li><a href="{% url 'logout' %}" class="btn" style="color: #D2C8C8; background-color: #404969;"type="submit" id="header-links"> Logout </a></li>
                  </ul>
              {% else %}
                <a href="{% url 'register' %}" class="btn" style="color: #D2C8C8; background-color: #404969;"type="submit" id="header-links"> Create Account </a>
                <a href="{% url 'login' %}" class="btn" style="color: #D2C8C8; background-color: #404969; margin-left: 10px; "type="submit" id="header-links">Log In</a>
              {% endif %}

            </div>
          </div>
        </div>
    </nav>
  </body>

  <!-- Notification -->

{#  <button id="notification" data-bs-target="#notificationModal" data-bs-toggle="modal"  class="btn" style="color:white; background-color: #fd5e14;"type="submit" id="header-links"> Skin101 Notification </button>#}
      <!-- Modal Popup Announcement -->
    <form method="GET" class="modal fade" id="notificationModal" data-keyboard="false" data-backdrop="static" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" style="color: #404969; font-size: 24px">Notification</h4>
          </div>
          <div class="modal-body">
            <h5 style="text-align: center; color: #A3816A; font-size: 19px">Hi, {{user.username}}! </h5>
            <br>
            <h5 style="text-align: center; color: #404969; font-size: 24px" id="notificationTitle">{{form.title}}</h5>
            <p style="text-align: center; color: #404969; font-size: 19px" id="notificationMessage">{{form.messages}}</p>
          </div>
          <div class="modal-footer">
            <button class="btn btn-info" data-dismiss="modal" style="color: #D2C8C8; background-color:#404969;" id="header-links" >Close</button>
          </div>
        </div>
      </div>
    </form>
    <!-- end modal -->

<script type="text/javascript">
$(document).ready(function() {
  $(document).on("submit", "#notificationModal", function (e) {
    e.preventDefault();
    var serializedData = $(this).serialize();
    var response = "";
    $.getJSON({
      type: 'GET',
      url: "{% url 'notification-datas' %}",
      data: serializedData,
      success: function (data) {
        $("#notificationTitle").text(data[data.length-1]["fields"]["title"].toLocaleString("en-US"));
        $("#notificationMessage").text(data[data.length-1]["fields"]["messages"].toLocaleString("en-US"));
        console.log("enable ajax..")
        alert("Check new notification!")
      },
      error: function (response) {
        console.log(response)
      }
    });
  });
});

//   $.getJSON("/administrator/notification-datas",
//   function(data){
//     $('#notificationTitle').text(data[data.length-1]["fields"]["title"].toLocaleString("en-US"));
//     $('#notificationMessage').text(data[data.length-1]["fields"]["messages"].toLocaleString("en-US"));
//   });
// })
</script>
</html>

notification/templates/set_notification.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Skin101 - Make Skincare Notification </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/notification_styles.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </head>
  <body id="notification">
    {% include 'navbar_roles.html' %}

    <!-- Make Notification -->
    <section class="container-fluid">
      <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-3">
          <form action="" method="POST" id="postformnotif" class="form-container">
              {% csrf_token %}
              <br>
              <div class="card" style="width: 50rem; margin-top: 30px; margin-left: -230px; padding-left: 20px; padding-right: 20px; padding-bottom: 30px; padding-top: 20px">
                  <h4 class="text-center font-weight-bold" style="color: #404969;">Set Notification</h4>
                  <br>
                  <div class="form-group">
                    <input id="id_title" class="form-control" width="75%" type="text" name="title" required="true" placeholder="Title" />
                  </div>
                  <div class="form-group">
                      <input id="id_messages" class="form-control" width="75%" type="text" name="messages" required="true" placeholder="Messages" />
                  </div>
                  <br>
                  <div class="d-flex justify-content-center">
                    <div class="order-1 p-2">
                      <button class="btn btn-outline-primary" type="submit" id="btnsavess" value="POST" style="padding-bottom: 10px">Post</button>
                    </div>
                    <div class="order-2 p-2">
                      <a href="/home" class="btn btn-outline-danger" id="btnsave" value="POST" style="padding-bottom: 10px">Cancel</a>
                    </div>
                </div>
              </div>
          </form>
        </section>
      </section>
    </section>

    <script type="text/javascript">
    $(document).ready(function() {
        $(document).on("submit", "#postformnotif", function(e){
            e.preventDefault();
            var serializedData = $(this).serialize();
            var response = "";
            $.ajax ({
                type : 'POST',
                url : "{% url 'set-notification' %}",
                data : serializedData,
                success : function(response){
                     $("#id_title").val(response["title"]);
                     $("#id_messages").val(response["messages"]);
                     console.log("checking notif ajax..")
                     alert("New notification has been published!")
                     window.location.href = "../home";
                },
                error : function(response){
                    console.log(response)
                }
            });

        });
    });
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>