quiz/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',start_session,name='start_session')
]

skin101/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import notification.urls as notification
import userprofile.urls as userprofile
import autentikasi.urls as autentikasi
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('notification.urls')),
    path('profile/', include('userprofile.urls')),
    path('', include('autentikasi.urls')),
    path('reviews/', include('reviews.urls')),
    path('quiz/',include('quiz.urls')),
    path('display/', include(('productdisplay.urls', 'productdisplay'))),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='user-profile'),
    path('edit-profile/', views.profileupdate, name='update-profile'), 
    path('profile/profile-datas/', views.profiledatas, name='profile-datas'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User #extending User models that django provided
from django.db.models.signals import post_save 
from django.contrib.auth.models import User
from django.dispatch import receiver #decorator catch the signal called post_save

from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # means: the user deleted, also the profile deleted in database(NOT for vice-versa)
    avatar = models.ImageField(default='default.jpg', upload_to='avatar_pict')
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} Profile' # out: username Profile

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # resize avatar to speed up website
        img = Image.open(self.avatar.path)
        if (img.height > 350 or img.width > 350):
            out_size = (350,350)
            img.thumbnail(out_size)
            img.save(self.avatar.path)

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from django.forms import widgets
from .models import Profile

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username',]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__' #show all
        exclude = ['user',]

userprofile/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .forms import ProfileUpdateForm, UserUpdateForm
from .models import Profile
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def profile(request):
    return render(request, 'profile.html')


@login_required
def profileupdate(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # profilelist = []
            # data_dict = {}
            # data_dict['name'] = request.POST.get('name')
            # data_dict['avatar'] = request.POST.get('avatar')
            # data_dict['email'] = request.POST.get('email')
            #
            # # data_dict.update(convert)
            # profilelist.append(data_dict)
            # return JsonResponse(data_dict, safe=False)
            messages.success(request, ('Your profile has been updated!'))
            return redirect('user-profile')
        else:
            messages.error(request, ('Unable to update your profile'))
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'edit_profile.html', context)

def profiledatas(request):
    form = Profile.objects.all()
    data = serializers.serialize('json', form)
    return HttpResponse(data, content_type='application/json')

userprofile/templates/base_profile.html
<!DOCTYPE html>
{% extends 'autentikasi/base.html' %}
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- TITLE -->
    <title> Profile </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- css for envelope logo -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  </head>
  <body>
    <!-- Page content-->
    <section class="py-5" style="background-color: #83aae1;font-family: 'Montserrat'">
      <div class="container">
        <div class="bg-opacity-50 rounded-3 py-5 px-4 px-md-5 mb-5">
          {% block content %} {% endblock content %}
        </div>
      </div> 
    </section>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

userprofile/templates/edit_profile.html
{% extends "base_profile.html" %} {% load crispy_forms_tags %} {% load static %} 

{% block content %}
{#<div class="img" style="background-image: url(https://i.postimg.cc/G2Jkj5WH/11-1-1.png); height: 300px;background-size: cover;">#}
<div class="img" style="background-color: white; opacity: 0%; height: 300px;background-size: cover;"></div>
</div>
<div class="card">
  <div class="card-body" style=" width: 70%; margin: auto; margin-top: -220px;">
      <div class="wrapper">
        <div id= "avatar-box" style="text-align: center;">
          <h2 class="card-title-desc" style="text-align: center; color: #404969;font-weight: bolder;">{{ user.profile.name }}</h2>
          <h4 class="card-title" style="text-align: center; color: #A3816A; ">@{{ user.username }}</h4>
          <img id="id_avatar" src="{{ user.profile.avatar.url }}" class="card-img-top" alt="profile picture"  style="object-fit:cover; width: 250px; height: 250px; border-radius: 50%; margin: 0 auto -60px;display: block; margin: 0 auto;">
          <div style="text-align: center; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px; background-color: #E6E7E5; margin-top:30px; margin-left:180px; margin-right:180px;">
            <!-- FORM -->
            <div class="row gx-5 justify-content-center" style="padding-left: 20px; padding-right: 20px; padding-bottom: 30px; padding-top: 30px>
              <div class="col-md-8">
                <!-- method -->
                <form method="POST" id="postform" enctype="multipart/form-data">
                  <div class="p-2">{{ profile_form.avatar|as_crispy_field }}</div>
                  {% csrf_token %}
                    <div class="form" id="the_post">
                    <!-- #1 -->
                      <div class="container">
                        <div class="d-flex justify-content-center">
                          <div class="order-1 p-2">{{ user_form|crispy }} </div>
                        </div>
                      </div>
                      <!-- #2 -->
                      <div class="container">
                        <div class="d-flex justify-content-center">
                          <divid class="order-1 p-2"> {{ profile_form.name|as_crispy_field }} </divid>
                          <div class="order-2 p-2"> {{ profile_form.email|as_crispy_field }} </div>
                        </div>
                      </div>
                      <br>
                  </div>
                  <div class="d-flex justify-content-center">
                    <div class="order-1 p-2">
                      <button class="btn btn-outline-primary" type="submit" id="btnsave" value="POST">Save Changes</button>
                    </div>
                    <div class="order-2 p-2">
                      <a href= "/profile" class="btn btn-outline-danger" type="reset" id="btncancel">Cancel</a>
                    </div>
                </div>
                </form>
              </div>
            </div>
      </div>
</div>
    <br>
    <footer>
    <div class="footer-container shadow p-3" style="background-color: #7A9EAF; bottom: 0px; top: 10px; margin-left: -206.5px; margin-right: -206.5px; margin-bottom: -17px">
      <p class="text-center footer-text" style="color: #D2C8C8; bottom: 0px;">
          Made by The Skincredibles <br>
          Copyright © 2022 RPL  University of Indonesia
      </p>
    </div>
    </footer>
{% endblock content %}

userprofile/templates/profile.html
{% extends "base_profile.html" %} {% load crispy_forms_tags %} {% load static %} 
{% block content %}

{% if user.is_authenticated %}
{#    <div class="img" style="background-image: url(https://i.postimg.cc/G2Jkj5WH/11-1-1.png); height: 300px;background-size: cover;"></div>#}
    <div class="img" style="background-color: white; opacity: 0%; height: 300px;background-size: cover;"></div>
        <div class="card">
            <div class="card-body" style=" width: 70%; margin: auto; margin-top: -150px;">
                <div class="wrapper">
                    <img src="{{ user.profile.avatar.url }}" class="card-img-top" alt="profile picture"  style="object-fit:cover; width: 250px; height: 250px; border-radius: 50%; margin: 0 auto -60px;display: block; margin: 0 auto;">
                </div>
            <div style="text-align: center; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px; background-color: #E6E7E5; margin-top:30px; margin-left:180px; margin-right:180px">
                <br>
                <h3 style="color:#404969" class="card-title">{{ user.profile.name }}</h3>
                <h5 style="color:#A3816A" class="card-text text-">@{{ user.username }}</h5>
                <hr style="width:100%; text-align:center;">
                <h6 class="card-text"><i class="fa fa-envelope" style="font-size:20px;color:#655989";></i><p style="color: #404969">{{ user.profile.email }}</p></h6>
                <h6 class="card-text" style="color: #404969"> Joined since: </h6>
                <p class="card-text text-secondary">{{ user.profile.created_at }}</p>
                <br>
                <a href= "/profile/edit-profile/" class="btn btn-outline-primary"> Edit Profile</a>
                <br>
                <br>
            </div>
        </div>
    <div>
    <footer>
    <div class="footer-container shadow p-3" style="background-color: #7A9EAF; bottom: 0px; top: 10px">
      <p class="text-center footer-text" style="color: #D2C8C8; bottom: 0px;">
          Made by The Skincredibles <br>
          Copyright © 2022 RPL  University of Indonesia
      </p>
    </div>
    </footer>
{% else %}
<h4> Please signup or login to see more! </h4>
{% endif %}
{% endblock content %}